### ISSUE TITLE
Wiki is out of date

### ISSUE THREAD

**Issue by eliTkos** [greghaynes/Afproto#6]
Hi greg,

Just bringing to your attention that the Wiki home page seems to contain outdated and contradictory information.

On the README.md (last edited three years ago):

A depiction of a frame:

| Start Byte | Escaped Data | Escaped CRC16 | End Byte |

(I read through the source code and can confirm this is correct)

Whereas on the wiki (last edited 2011):

Each packet is in the following format

| Header Byte | Length (1 byte) | CRC (1 byte) | Escaped Message (N bytes) | End Byte |

For large messages there is a special case where length is set to 0x00.

| Header Byte | 0x00 (1 byte) | Length (2 byte) | CRC (1 byte) | Escaped Message (N bytes) | End Byte |

Which seems to not currently be correct

Thanks!

Eli

**Comment by eliTkos** [comment]
Never Mind I just found the "arduino" branch with the alternative message structure

I noticed in the wiki you specified embedded C which would refer to the "arduino" branch

I'll close this
Thanks

**Comment by greghaynes** [comment]
@eliTkos Thanks for pointing this out - Feel free to submit a PR to document this branch structure.

**Comment by eliTkos** [comment]
@greghaynes  Thanks! I forked the repo and wrote an edited wiki page here:

https://github.com/eliTkos/Afproto/wiki

There doesn't seem to be a way to submit a PR directly on a wiki with the Gihub UI but feel free to leave feedback and copy what you agree with

Thanks again,
-Eli

**Comment by greghaynes** [comment]
Thanks! That looks great to me. I've added you as a collaborator and hopefully you can edit the wiki now.

**Comment by eliTkos** [comment]
Hi Greg

Edited!

Thanks!

Eli
